Table Users {
  id_users serial [pk]
  username varchar [unique]
  email varchar
  contrasena varchar(10)
}
Table Planes {
id_planes    serial [pk]
  id_users_planes int
  nombre_planes varchar
  precio_usd  decimal
}
Table Suscripciones {
  id_suscripciones  serial [pk]
  usuario  varchar
  plan        text
  fecha_inicio int
  fecha_fin    int
}
Table Pagos {
  id_pagos       serial [pk]
  suscripcion_hd varchar
  monto_usd   decimal
  estado      varchar
  pagado      varchar
}
Table EstadoPago {
  id_estado_pago  serial [pk]
  completado varchar
}
Table Perfiles {
  id_perfiles       serial [pk]
  usuario           varchar
  programas         text
  edad              int
  idioma            varchar
  historial         text

}
Table Busqueda {
  id_busqueda         serial [pk]
  nombre_titulo       text
  tipo                text
  generos             text
  sinopsis            text
  ano_estreno         int
}
Table Tipos {
  id_tipos  serial [pk]
  tipo_d_programa varchar
  peliculas text
  series    text
}

Table Generos {
  id_generos serial [pk]
  busqueda_d_genero varchar
  terror   varchar
  accion   varchar
  romance varchar
  anime varchar
  risa varchar
  documentales varchar
}
Table Historial {
  id_historial    serial [pk]
  titulo         varchar
  episodio       varchar
  visto_en       varchar
}

Ref: Users.id_users < Planes.id_users_planes
Ref: Users.username < Perfiles.usuario
Ref: Planes.precio_usd < Suscripciones.plan
Ref: Suscripciones.usuario < Pagos.suscripcion_hd
Ref: Pagos.estado < EstadoPago.completado
Ref: Perfiles.programas < Busqueda.nombre_titulo
Ref: Busqueda.tipo < Tipos.tipo_d_programa
Ref: Busqueda.generos < Generos.busqueda_d_genero
Ref: Perfiles.historial < Historial.titulo